using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace Week5
{
    public partial class frmDisplayAuthors : Form
    {
        public frmDisplayAuthors()
        {
            InitializeComponent();
        }

        //DataContext object is used to interact with the database.
        //The BooksDataContext class was automatically generated by the IDE when you created
        //the LINQ to SQL classes to allow access to the Books database
        // LINQ to SQL data context
        private BooksDataContext database = new BooksDataContext();

        private void frmDisplayAuthors_Load(object sender, EventArgs e)
        {
            // use LINQ to order the data for display
            authorBindingSource.DataSource =
                                                from author in database.Authors
                                                orderby author.AuthorID
                                                select author;
        }

        //Select the Save on the form naigation and double click event click
        //Set Enable = true on teh Save button
        private void authorBindingNavigatorSaveItem_Click(object sender, EventArgs e)
        {
            Validate(); // validate input fields
            authorBindingSource.EndEdit(); // indicate edits are complete
            database.SubmitChanges(); // write changes to database file
        }

    }
}
