<?xml version="1.0" encoding="utf-8"?><Database Name="Movies" Class="LINQMoviesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\App_Data\Movies.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="Week5.My.MySettings" SettingsPropertyName="MoviesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Movie" Member="Movies">
    <Type Name="Movie">
      <Column Name="MovieId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MovieName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="YearPublished" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>